# Generated by Django 5.0.4 on 2024-04-12 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('camera', 'Camera'), ('video_file', 'Video File')], max_length=15)),
                ('camera_id', models.PositiveSmallIntegerField(default=0)),
                ('center_x_plus_minus', models.PositiveSmallIntegerField(default=100)),
                ('predection_threshold', models.FloatField(default=0.001)),
                ('predection_confidence', models.FloatField(default=0.8)),
                ('show_detections', models.BooleanField(default=False)),
                ('frame_update_delay', models.FloatField(default=0.1)),
                ('mqtt_broker', models.CharField(default='localhost', max_length=50)),
                ('mqtt_port', models.PositiveSmallIntegerField(default=1883)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='video_samples/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
